// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

#include <bits/stdc++.h>
using namespace std;

char findDifference(string s, string t)
{
    map<char, int> m;
    map<char, int>::iterator it;

    for (char c : s)
    {
        it = m.find(c);    // searching where character c of s is already present in the map
        if (it != m.end()) // not the end and found the character
        {
            it->second++;
        }
        else // new character in the map, so insert it into map
        {
            m.insert({c, 1});
        }
    }

    for (char e : t) // if the dtring t is present then delete that eleement from the map
    {
        it = m.find(e);
        if (it != m.end()) // if the element is there in the map then decrement the count
        {
            it->second--;
        }
        else // if excess element ie: no existence in the string s but there in t.
            return e;
    }

    for (it = m.begin(); it != m.end(); it++)//any element in excess
    {
        if(it->second!=0)
        {
            return it->first;
        }
    }
    return 'a';
}
    int main()
    {
        string s = "abcd";
        string t = "abcde";
        cout << findDifference(s, t);
        return 0;
    }