// Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by
// deleting some character of a given string without changing its order.

// Examples:

// Input : abc
// Output : a, b, c, ab, bc, ac, abc

// Input : aaa
// Output : a, a, a, aa, aa, aa, aaa

#include <bits/stdc++.h>
using namespace std;

int subsequence(string str, string output[])
{
    if (str.length() == 0)
    {
        // empty string
        output[0] = ""; // even and empty string is a substring
        return 1;
    }

    int smallerOutputSize = subsequence(str.substr(1), output); // except for the first string rest all the other other string's size is present.
    for (int i = 0; i < smallerOutputSize; i++)
    {
        output[i + smallerOutputSize] = str[0] + output[i];
    }
    return 2 * smallerOutputSize;
}

int main()
{
    string output[1000];

    int outputSize = subsequence("abc", output);
    for (int i = 0; i < outputSize; i++)
    {
        cout << output[i] << endl;
    }
    return 0;
}